#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 102
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 17

enum {
  anon_sym_let = 1,
  anon_sym_EQ = 2,
  anon_sym_const = 3,
  anon_sym_type = 4,
  anon_sym_number = 5,
  anon_sym_string = 6,
  anon_sym_boolean = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  anon_sym_EQ_GT = 10,
  anon_sym_COMMA = 11,
  anon_sym_PLUS = 12,
  sym__lower_identifier = 13,
  sym__upper_identifier = 14,
  sym_string_literal = 15,
  sym_number = 16,
  sym_comment = 17,
  anon_sym_LBRACK = 18,
  anon_sym_RBRACK = 19,
  anon_sym_LBRACE = 20,
  anon_sym_RBRACE = 21,
  anon_sym_COLON = 22,
  anon_sym_PIPE = 23,
  sym_source_file = 24,
  sym__statement = 25,
  sym_let_assignment = 26,
  sym_const_declaration = 27,
  sym_type_definition = 28,
  sym__type_expression = 29,
  sym_primitive_type = 30,
  sym_type_identifier = 31,
  sym__expression = 32,
  sym__primary_expression = 33,
  sym_function_expression = 34,
  sym_call_expression = 35,
  sym_parameter_list = 36,
  sym_binary_expression = 37,
  sym_identifier = 38,
  sym_tuple_type = 39,
  sym_record_type = 40,
  sym_record_field = 41,
  sym_adt_type = 42,
  sym_adt_option = 43,
  sym_adt_fields = 44,
  sym_adt_field = 45,
  aux_sym_source_file_repeat1 = 46,
  aux_sym_call_expression_repeat1 = 47,
  aux_sym_parameter_list_repeat1 = 48,
  aux_sym_tuple_type_repeat1 = 49,
  aux_sym_record_type_repeat1 = 50,
  aux_sym_adt_type_repeat1 = 51,
  aux_sym_adt_fields_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_const] = "const",
  [anon_sym_type] = "type",
  [anon_sym_number] = "number",
  [anon_sym_string] = "string",
  [anon_sym_boolean] = "boolean",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_COMMA] = ",",
  [anon_sym_PLUS] = "+",
  [sym__lower_identifier] = "_lower_identifier",
  [sym__upper_identifier] = "_upper_identifier",
  [sym_string_literal] = "string_literal",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_PIPE] = "|",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_let_assignment] = "let_assignment",
  [sym_const_declaration] = "const_declaration",
  [sym_type_definition] = "type_definition",
  [sym__type_expression] = "_type_expression",
  [sym_primitive_type] = "primitive_type",
  [sym_type_identifier] = "type_identifier",
  [sym__expression] = "_expression",
  [sym__primary_expression] = "_primary_expression",
  [sym_function_expression] = "function_expression",
  [sym_call_expression] = "call_expression",
  [sym_parameter_list] = "parameter_list",
  [sym_binary_expression] = "binary_expression",
  [sym_identifier] = "identifier",
  [sym_tuple_type] = "tuple_type",
  [sym_record_type] = "record_type",
  [sym_record_field] = "record_field",
  [sym_adt_type] = "adt_type",
  [sym_adt_option] = "adt_option",
  [sym_adt_fields] = "adt_fields",
  [sym_adt_field] = "adt_field",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_call_expression_repeat1] = "call_expression_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_tuple_type_repeat1] = "tuple_type_repeat1",
  [aux_sym_record_type_repeat1] = "record_type_repeat1",
  [aux_sym_adt_type_repeat1] = "adt_type_repeat1",
  [aux_sym_adt_fields_repeat1] = "adt_fields_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_number] = anon_sym_number,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_boolean] = anon_sym_boolean,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [sym__lower_identifier] = sym__lower_identifier,
  [sym__upper_identifier] = sym__upper_identifier,
  [sym_string_literal] = sym_string_literal,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_let_assignment] = sym_let_assignment,
  [sym_const_declaration] = sym_const_declaration,
  [sym_type_definition] = sym_type_definition,
  [sym__type_expression] = sym__type_expression,
  [sym_primitive_type] = sym_primitive_type,
  [sym_type_identifier] = sym_type_identifier,
  [sym__expression] = sym__expression,
  [sym__primary_expression] = sym__primary_expression,
  [sym_function_expression] = sym_function_expression,
  [sym_call_expression] = sym_call_expression,
  [sym_parameter_list] = sym_parameter_list,
  [sym_binary_expression] = sym_binary_expression,
  [sym_identifier] = sym_identifier,
  [sym_tuple_type] = sym_tuple_type,
  [sym_record_type] = sym_record_type,
  [sym_record_field] = sym_record_field,
  [sym_adt_type] = sym_adt_type,
  [sym_adt_option] = sym_adt_option,
  [sym_adt_fields] = sym_adt_fields,
  [sym_adt_field] = sym_adt_field,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_call_expression_repeat1] = aux_sym_call_expression_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_tuple_type_repeat1] = aux_sym_tuple_type_repeat1,
  [aux_sym_record_type_repeat1] = aux_sym_record_type_repeat1,
  [aux_sym_adt_type_repeat1] = aux_sym_adt_type_repeat1,
  [aux_sym_adt_fields_repeat1] = aux_sym_adt_fields_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_number] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_boolean] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym__lower_identifier] = {
    .visible = false,
    .named = true,
  },
  [sym__upper_identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_const_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__type_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__primary_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_function_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_type] = {
    .visible = true,
    .named = true,
  },
  [sym_record_type] = {
    .visible = true,
    .named = true,
  },
  [sym_record_field] = {
    .visible = true,
    .named = true,
  },
  [sym_adt_type] = {
    .visible = true,
    .named = true,
  },
  [sym_adt_option] = {
    .visible = true,
    .named = true,
  },
  [sym_adt_fields] = {
    .visible = true,
    .named = true,
  },
  [sym_adt_field] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tuple_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_adt_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_adt_fields_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_arguments = 1,
  field_body = 2,
  field_fields = 3,
  field_function = 4,
  field_left = 5,
  field_name = 6,
  field_options = 7,
  field_parameters = 8,
  field_right = 9,
  field_type = 10,
  field_value = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_body] = "body",
  [field_fields] = "fields",
  [field_function] = "function",
  [field_left] = "left",
  [field_name] = "name",
  [field_options] = "options",
  [field_parameters] = "parameters",
  [field_right] = "right",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 1},
  [7] = {.index = 9, .length = 1},
  [8] = {.index = 10, .length = 2},
  [9] = {.index = 12, .length = 1},
  [10] = {.index = 13, .length = 2},
  [11] = {.index = 15, .length = 2},
  [12] = {.index = 17, .length = 2},
  [13] = {.index = 19, .length = 1},
  [14] = {.index = 20, .length = 1},
  [15] = {.index = 21, .length = 2},
  [16] = {.index = 23, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
    {field_value, 3},
  [2] =
    {field_options, 0},
  [3] =
    {field_options, 1},
  [4] =
    {field_options, 0},
    {field_options, 1},
  [6] =
    {field_left, 0},
    {field_right, 2},
  [8] =
    {field_function, 0},
  [9] =
    {field_fields, 1},
  [10] =
    {field_options, 1},
    {field_options, 2},
  [12] =
    {field_body, 3},
  [13] =
    {field_arguments, 2},
    {field_function, 0},
  [15] =
    {field_fields, 1},
    {field_fields, 2},
  [17] =
    {field_name, 0},
    {field_type, 2},
  [19] =
    {field_type, 2},
  [20] =
    {field_fields, 2},
  [21] =
    {field_body, 4},
    {field_parameters, 1},
  [23] =
    {field_arguments, 2},
    {field_arguments, 3},
    {field_function, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(33);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(42);
      if (lookahead == ')') ADVANCE(43);
      if (lookahead == '+') ADVANCE(46);
      if (lookahead == ',') ADVANCE(45);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ':') ADVANCE(57);
      if (lookahead == '=') ADVANCE(36);
      if (lookahead == '[') ADVANCE(53);
      if (lookahead == ']') ADVANCE(54);
      if (lookahead == 'b') ADVANCE(22);
      if (lookahead == 'c') ADVANCE(20);
      if (lookahead == 'l') ADVANCE(11);
      if (lookahead == 'n') ADVANCE(30);
      if (lookahead == 's') ADVANCE(27);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '{') ADVANCE(55);
      if (lookahead == '|') ADVANCE(58);
      if (lookahead == '}') ADVANCE(56);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(48);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(42);
      if (lookahead == ')') ADVANCE(43);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '}') ADVANCE(56);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(48);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(49);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(52);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(51);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(44);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'b') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 13:
      if (lookahead == 'g') ADVANCE(40);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 16:
      if (lookahead == 'm') ADVANCE(8);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 23:
      if (lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 30:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 31:
      if (lookahead == 'y') ADVANCE(23);
      END_STATE();
    case 32:
      if (eof) ADVANCE(33);
      if (lookahead == '(') ADVANCE(42);
      if (lookahead == ')') ADVANCE(43);
      if (lookahead == '+') ADVANCE(46);
      if (lookahead == ',') ADVANCE(45);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ':') ADVANCE(57);
      if (lookahead == '=') ADVANCE(35);
      if (lookahead == ']') ADVANCE(54);
      if (lookahead == 'c') ADVANCE(20);
      if (lookahead == 'l') ADVANCE(11);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '|') ADVANCE(58);
      if (lookahead == '}') ADVANCE(56);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(32)
      END_STATE();
    case 33:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(44);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_number);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_boolean);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym__lower_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__upper_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 32},
  [16] = {.lex_state = 32},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 32},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 32},
  [91] = {.lex_state = 32},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_number] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_boolean] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [sym__upper_identifier] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(101),
    [sym__statement] = STATE(18),
    [sym_let_assignment] = STATE(18),
    [sym_const_declaration] = STATE(18),
    [sym_type_definition] = STATE(18),
    [aux_sym_source_file_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_let] = ACTIONS(7),
    [anon_sym_const] = ACTIONS(9),
    [anon_sym_type] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_RBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    STATE(19), 1,
      sym_adt_option,
    STATE(20), 1,
      sym_type_identifier,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
    STATE(85), 5,
      sym__type_expression,
      sym_primitive_type,
      sym_tuple_type,
      sym_record_type,
      sym_adt_type,
  [37] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(25), 1,
      anon_sym_RBRACK,
    STATE(19), 1,
      sym_adt_option,
    STATE(20), 1,
      sym_type_identifier,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
    STATE(85), 5,
      sym__type_expression,
      sym_primitive_type,
      sym_tuple_type,
      sym_record_type,
      sym_adt_type,
  [74] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    STATE(19), 1,
      sym_adt_option,
    STATE(20), 1,
      sym_type_identifier,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
    STATE(60), 5,
      sym__type_expression,
      sym_primitive_type,
      sym_tuple_type,
      sym_record_type,
      sym_adt_type,
  [108] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    STATE(19), 1,
      sym_adt_option,
    STATE(20), 1,
      sym_type_identifier,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
    STATE(58), 5,
      sym__type_expression,
      sym_primitive_type,
      sym_tuple_type,
      sym_record_type,
      sym_adt_type,
  [142] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    STATE(19), 1,
      sym_adt_option,
    STATE(20), 1,
      sym_type_identifier,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
    STATE(83), 5,
      sym__type_expression,
      sym_primitive_type,
      sym_tuple_type,
      sym_record_type,
      sym_adt_type,
  [176] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    STATE(19), 1,
      sym_adt_option,
    STATE(20), 1,
      sym_type_identifier,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
    STATE(85), 5,
      sym__type_expression,
      sym_primitive_type,
      sym_tuple_type,
      sym_record_type,
      sym_adt_type,
  [210] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      sym_identifier,
    ACTIONS(31), 2,
      sym__lower_identifier,
      sym__upper_identifier,
    ACTIONS(33), 2,
      sym_string_literal,
      sym_number,
    STATE(55), 5,
      sym__expression,
      sym__primary_expression,
      sym_function_expression,
      sym_call_expression,
      sym_binary_expression,
  [238] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    STATE(27), 1,
      sym_identifier,
    ACTIONS(31), 2,
      sym__lower_identifier,
      sym__upper_identifier,
    ACTIONS(35), 2,
      sym_string_literal,
      sym_number,
    STATE(47), 5,
      sym__expression,
      sym__primary_expression,
      sym_function_expression,
      sym_call_expression,
      sym_binary_expression,
  [263] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    STATE(27), 1,
      sym_identifier,
    ACTIONS(31), 2,
      sym__lower_identifier,
      sym__upper_identifier,
    ACTIONS(37), 2,
      sym_string_literal,
      sym_number,
    STATE(49), 5,
      sym__expression,
      sym__primary_expression,
      sym_function_expression,
      sym_call_expression,
      sym_binary_expression,
  [288] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    STATE(27), 1,
      sym_identifier,
    ACTIONS(31), 2,
      sym__lower_identifier,
      sym__upper_identifier,
    ACTIONS(39), 2,
      sym_string_literal,
      sym_number,
    STATE(32), 5,
      sym__expression,
      sym__primary_expression,
      sym_function_expression,
      sym_call_expression,
      sym_binary_expression,
  [313] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    STATE(27), 1,
      sym_identifier,
    ACTIONS(31), 2,
      sym__lower_identifier,
      sym__upper_identifier,
    ACTIONS(41), 2,
      sym_string_literal,
      sym_number,
    STATE(74), 5,
      sym__expression,
      sym__primary_expression,
      sym_function_expression,
      sym_call_expression,
      sym_binary_expression,
  [338] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    STATE(27), 1,
      sym_identifier,
    ACTIONS(31), 2,
      sym__lower_identifier,
      sym__upper_identifier,
    ACTIONS(43), 2,
      sym_string_literal,
      sym_number,
    STATE(43), 5,
      sym__expression,
      sym__primary_expression,
      sym_function_expression,
      sym_call_expression,
      sym_binary_expression,
  [363] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    STATE(27), 1,
      sym_identifier,
    ACTIONS(31), 2,
      sym__lower_identifier,
      sym__upper_identifier,
    ACTIONS(45), 2,
      sym_string_literal,
      sym_number,
    STATE(36), 5,
      sym__expression,
      sym__primary_expression,
      sym_function_expression,
      sym_call_expression,
      sym_binary_expression,
  [388] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 10,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_EQ,
      anon_sym_const,
      anon_sym_type,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_COLON,
  [404] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 10,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_EQ,
      anon_sym_const,
      anon_sym_type,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [420] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      anon_sym_let,
    ACTIONS(56), 1,
      anon_sym_const,
    ACTIONS(59), 1,
      anon_sym_type,
    STATE(17), 5,
      sym__statement,
      sym_let_assignment,
      sym_const_declaration,
      sym_type_definition,
      aux_sym_source_file_repeat1,
  [443] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_const,
    ACTIONS(11), 1,
      anon_sym_type,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    STATE(17), 5,
      sym__statement,
      sym_let_assignment,
      sym_const_declaration,
      sym_type_definition,
      aux_sym_source_file_repeat1,
  [466] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_PIPE,
    STATE(23), 1,
      aux_sym_adt_type_repeat1,
    ACTIONS(64), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [485] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 1,
      anon_sym_PIPE,
    ACTIONS(68), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [504] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [521] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_PIPE,
    STATE(25), 1,
      aux_sym_adt_type_repeat1,
    ACTIONS(75), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [540] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_PIPE,
    STATE(25), 1,
      aux_sym_adt_type_repeat1,
    ACTIONS(77), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [559] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_PIPE,
    STATE(22), 1,
      aux_sym_adt_type_repeat1,
    ACTIONS(79), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [578] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_PIPE,
    STATE(25), 1,
      aux_sym_adt_type_repeat1,
    ACTIONS(81), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [597] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [611] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
  [627] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [641] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [655] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [669] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
  [682] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
  [695] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [708] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [721] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
  [734] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_PLUS,
    ACTIONS(106), 6,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [749] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
  [762] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [775] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [788] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [801] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [814] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [827] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_PLUS,
    ACTIONS(122), 6,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [842] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [855] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    STATE(92), 1,
      sym_primitive_type,
    STATE(93), 1,
      sym_adt_fields,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
  [873] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    STATE(84), 2,
      sym_primitive_type,
      sym_type_identifier,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
  [889] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_PLUS,
    ACTIONS(128), 4,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
  [902] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      sym_identifier,
    STATE(96), 1,
      sym_parameter_list,
    ACTIONS(31), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [919] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_PLUS,
    ACTIONS(132), 4,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
  [932] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      sym_record_field,
    STATE(97), 1,
      sym_identifier,
    ACTIONS(31), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [949] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_adt_field,
    STATE(94), 1,
      sym_identifier,
    ACTIONS(31), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [966] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      sym_record_field,
    STATE(97), 1,
      sym_identifier,
    ACTIONS(31), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [983] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_adt_field,
    STATE(94), 1,
      sym_identifier,
    ACTIONS(31), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [1000] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(80), 1,
      sym_adt_field,
    STATE(94), 1,
      sym_identifier,
    ACTIONS(31), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [1014] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_PLUS,
    ACTIONS(142), 1,
      anon_sym_RPAREN,
    ACTIONS(144), 1,
      anon_sym_COMMA,
    STATE(64), 1,
      aux_sym_call_expression_repeat1,
  [1030] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(78), 1,
      sym_record_field,
    STATE(97), 1,
      sym_identifier,
    ACTIONS(31), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [1044] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(71), 1,
      sym_adt_field,
    STATE(94), 1,
      sym_identifier,
    ACTIONS(31), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [1058] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 4,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
  [1068] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(82), 1,
      sym_record_field,
    STATE(97), 1,
      sym_identifier,
    ACTIONS(31), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [1082] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_COMMA,
    ACTIONS(150), 1,
      anon_sym_RBRACK,
    STATE(65), 1,
      aux_sym_tuple_type_repeat1,
  [1095] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    ACTIONS(155), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      aux_sym_adt_fields_repeat1,
  [1108] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_RPAREN,
    ACTIONS(159), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_parameter_list_repeat1,
  [1121] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(91), 1,
      sym_identifier,
    ACTIONS(31), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [1132] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_COMMA,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_call_expression_repeat1,
  [1145] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    ACTIONS(166), 1,
      anon_sym_RBRACK,
    STATE(66), 1,
      aux_sym_tuple_type_repeat1,
  [1158] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_COMMA,
    ACTIONS(171), 1,
      anon_sym_RBRACK,
    STATE(66), 1,
      aux_sym_tuple_type_repeat1,
  [1171] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(81), 1,
      sym_identifier,
    ACTIONS(31), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [1182] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_RPAREN,
    ACTIONS(175), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_parameter_list_repeat1,
  [1195] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    ACTIONS(179), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      aux_sym_record_type_repeat1,
  [1208] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    ACTIONS(184), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      aux_sym_record_type_repeat1,
  [1221] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    ACTIONS(188), 1,
      anon_sym_RBRACE,
    STATE(79), 1,
      aux_sym_adt_fields_repeat1,
  [1234] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_COMMA,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      aux_sym_parameter_list_repeat1,
  [1247] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    STATE(21), 1,
      sym_type_identifier,
    STATE(28), 1,
      sym_adt_option,
  [1260] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_PLUS,
    ACTIONS(192), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1271] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(90), 1,
      sym_identifier,
    ACTIONS(31), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [1282] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_RPAREN,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_call_expression_repeat1,
  [1295] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    STATE(21), 1,
      sym_type_identifier,
    STATE(24), 1,
      sym_adt_option,
  [1308] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    ACTIONS(199), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_record_type_repeat1,
  [1321] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_COMMA,
    ACTIONS(203), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      aux_sym_adt_fields_repeat1,
  [1334] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1342] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1350] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1358] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1366] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1374] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1382] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    STATE(88), 1,
      sym_type_identifier,
  [1392] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_EQ_GT,
  [1399] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_EQ,
  [1406] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_EQ_GT,
  [1413] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_EQ,
  [1420] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_EQ,
  [1427] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
  [1434] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
  [1441] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_COLON,
  [1448] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
  [1455] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_RPAREN,
  [1462] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_COLON,
  [1469] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_RPAREN,
  [1476] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_RPAREN,
  [1483] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_RPAREN,
  [1490] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 74,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 142,
  [SMALL_STATE(7)] = 176,
  [SMALL_STATE(8)] = 210,
  [SMALL_STATE(9)] = 238,
  [SMALL_STATE(10)] = 263,
  [SMALL_STATE(11)] = 288,
  [SMALL_STATE(12)] = 313,
  [SMALL_STATE(13)] = 338,
  [SMALL_STATE(14)] = 363,
  [SMALL_STATE(15)] = 388,
  [SMALL_STATE(16)] = 404,
  [SMALL_STATE(17)] = 420,
  [SMALL_STATE(18)] = 443,
  [SMALL_STATE(19)] = 466,
  [SMALL_STATE(20)] = 485,
  [SMALL_STATE(21)] = 504,
  [SMALL_STATE(22)] = 521,
  [SMALL_STATE(23)] = 540,
  [SMALL_STATE(24)] = 559,
  [SMALL_STATE(25)] = 578,
  [SMALL_STATE(26)] = 597,
  [SMALL_STATE(27)] = 611,
  [SMALL_STATE(28)] = 627,
  [SMALL_STATE(29)] = 641,
  [SMALL_STATE(30)] = 655,
  [SMALL_STATE(31)] = 669,
  [SMALL_STATE(32)] = 682,
  [SMALL_STATE(33)] = 695,
  [SMALL_STATE(34)] = 708,
  [SMALL_STATE(35)] = 721,
  [SMALL_STATE(36)] = 734,
  [SMALL_STATE(37)] = 749,
  [SMALL_STATE(38)] = 762,
  [SMALL_STATE(39)] = 775,
  [SMALL_STATE(40)] = 788,
  [SMALL_STATE(41)] = 801,
  [SMALL_STATE(42)] = 814,
  [SMALL_STATE(43)] = 827,
  [SMALL_STATE(44)] = 842,
  [SMALL_STATE(45)] = 855,
  [SMALL_STATE(46)] = 873,
  [SMALL_STATE(47)] = 889,
  [SMALL_STATE(48)] = 902,
  [SMALL_STATE(49)] = 919,
  [SMALL_STATE(50)] = 932,
  [SMALL_STATE(51)] = 949,
  [SMALL_STATE(52)] = 966,
  [SMALL_STATE(53)] = 983,
  [SMALL_STATE(54)] = 1000,
  [SMALL_STATE(55)] = 1014,
  [SMALL_STATE(56)] = 1030,
  [SMALL_STATE(57)] = 1044,
  [SMALL_STATE(58)] = 1058,
  [SMALL_STATE(59)] = 1068,
  [SMALL_STATE(60)] = 1082,
  [SMALL_STATE(61)] = 1095,
  [SMALL_STATE(62)] = 1108,
  [SMALL_STATE(63)] = 1121,
  [SMALL_STATE(64)] = 1132,
  [SMALL_STATE(65)] = 1145,
  [SMALL_STATE(66)] = 1158,
  [SMALL_STATE(67)] = 1171,
  [SMALL_STATE(68)] = 1182,
  [SMALL_STATE(69)] = 1195,
  [SMALL_STATE(70)] = 1208,
  [SMALL_STATE(71)] = 1221,
  [SMALL_STATE(72)] = 1234,
  [SMALL_STATE(73)] = 1247,
  [SMALL_STATE(74)] = 1260,
  [SMALL_STATE(75)] = 1271,
  [SMALL_STATE(76)] = 1282,
  [SMALL_STATE(77)] = 1295,
  [SMALL_STATE(78)] = 1308,
  [SMALL_STATE(79)] = 1321,
  [SMALL_STATE(80)] = 1334,
  [SMALL_STATE(81)] = 1342,
  [SMALL_STATE(82)] = 1350,
  [SMALL_STATE(83)] = 1358,
  [SMALL_STATE(84)] = 1366,
  [SMALL_STATE(85)] = 1374,
  [SMALL_STATE(86)] = 1382,
  [SMALL_STATE(87)] = 1392,
  [SMALL_STATE(88)] = 1399,
  [SMALL_STATE(89)] = 1406,
  [SMALL_STATE(90)] = 1413,
  [SMALL_STATE(91)] = 1420,
  [SMALL_STATE(92)] = 1427,
  [SMALL_STATE(93)] = 1434,
  [SMALL_STATE(94)] = 1441,
  [SMALL_STATE(95)] = 1448,
  [SMALL_STATE(96)] = 1455,
  [SMALL_STATE(97)] = 1462,
  [SMALL_STATE(98)] = 1469,
  [SMALL_STATE(99)] = 1476,
  [SMALL_STATE(100)] = 1483,
  [SMALL_STATE(101)] = 1490,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_identifier, 1),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(63),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(75),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(86),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_type, 1, .production_id = 2),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__type_expression, 1), REDUCE(sym_adt_option, 1),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_option, 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_type, 3, .production_id = 8),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_type, 2, .production_id = 4),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_type, 2, .production_id = 3),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_adt_type_repeat1, 2),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_adt_type_repeat1, 2), SHIFT_REPEAT(73),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary_expression, 1),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_option, 4, .production_id = 13),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_option, 4, .production_id = 14),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 5, .production_id = 16),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 5),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 3, .production_id = 7),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 3, .production_id = 7),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 3, .production_id = 6),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_expression, 4, .production_id = 9),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 4, .production_id = 10),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 4, .production_id = 7),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 4, .production_id = 11),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 4, .production_id = 7),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 5, .production_id = 11),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 4, .production_id = 11),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_expression, 5, .production_id = 15),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 5, .production_id = 11),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_declaration, 4, .production_id = 1),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_assignment, 4, .production_id = 1),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 4, .production_id = 1),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_adt_fields_repeat1, 2), SHIFT_REPEAT(54),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_adt_fields_repeat1, 2),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(67),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2), SHIFT_REPEAT(7),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_type_repeat1, 2), SHIFT_REPEAT(59),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_type_repeat1, 2),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2), SHIFT_REPEAT(12),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_field, 3, .production_id = 12),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_field, 3, .production_id = 12),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_fields, 3, .production_id = 7),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_fields, 4, .production_id = 11),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_fields, 4, .production_id = 7),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_fields, 5, .production_id = 11),
  [237] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_chicory(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
