#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 92
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 14

enum {
  anon_sym_let = 1,
  anon_sym_EQ = 2,
  anon_sym_const = 3,
  anon_sym_type = 4,
  anon_sym_number = 5,
  anon_sym_string = 6,
  anon_sym_boolean = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  anon_sym_EQ_GT = 10,
  anon_sym_COMMA = 11,
  anon_sym_PLUS = 12,
  sym__lower_identifier = 13,
  sym__upper_identifier = 14,
  sym_string_literal = 15,
  sym_number = 16,
  sym_comment = 17,
  anon_sym_LBRACK = 18,
  anon_sym_RBRACK = 19,
  anon_sym_LBRACE = 20,
  anon_sym_RBRACE = 21,
  anon_sym_COLON = 22,
  anon_sym_PIPE = 23,
  sym_source_file = 24,
  sym__statement = 25,
  sym_let_assignment = 26,
  sym_const_declaration = 27,
  sym_type_definition = 28,
  sym__type_expression = 29,
  sym_primitive_type = 30,
  sym_type_identifier = 31,
  sym__expression = 32,
  sym__primary_expression = 33,
  sym_function_expression = 34,
  sym_parameter_list = 35,
  sym_binary_expression = 36,
  sym_identifier = 37,
  sym_tuple_type = 38,
  sym_record_type = 39,
  sym_record_field = 40,
  sym_adt_type = 41,
  sym_adt_option = 42,
  sym_adt_fields = 43,
  sym_adt_field = 44,
  aux_sym_source_file_repeat1 = 45,
  aux_sym_parameter_list_repeat1 = 46,
  aux_sym_tuple_type_repeat1 = 47,
  aux_sym_record_type_repeat1 = 48,
  aux_sym_adt_type_repeat1 = 49,
  aux_sym_adt_fields_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_const] = "const",
  [anon_sym_type] = "type",
  [anon_sym_number] = "number",
  [anon_sym_string] = "string",
  [anon_sym_boolean] = "boolean",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_COMMA] = ",",
  [anon_sym_PLUS] = "+",
  [sym__lower_identifier] = "_lower_identifier",
  [sym__upper_identifier] = "_upper_identifier",
  [sym_string_literal] = "string_literal",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_PIPE] = "|",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_let_assignment] = "let_assignment",
  [sym_const_declaration] = "const_declaration",
  [sym_type_definition] = "type_definition",
  [sym__type_expression] = "_type_expression",
  [sym_primitive_type] = "primitive_type",
  [sym_type_identifier] = "type_identifier",
  [sym__expression] = "_expression",
  [sym__primary_expression] = "_primary_expression",
  [sym_function_expression] = "function_expression",
  [sym_parameter_list] = "parameter_list",
  [sym_binary_expression] = "binary_expression",
  [sym_identifier] = "identifier",
  [sym_tuple_type] = "tuple_type",
  [sym_record_type] = "record_type",
  [sym_record_field] = "record_field",
  [sym_adt_type] = "adt_type",
  [sym_adt_option] = "adt_option",
  [sym_adt_fields] = "adt_fields",
  [sym_adt_field] = "adt_field",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_tuple_type_repeat1] = "tuple_type_repeat1",
  [aux_sym_record_type_repeat1] = "record_type_repeat1",
  [aux_sym_adt_type_repeat1] = "adt_type_repeat1",
  [aux_sym_adt_fields_repeat1] = "adt_fields_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_number] = anon_sym_number,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_boolean] = anon_sym_boolean,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [sym__lower_identifier] = sym__lower_identifier,
  [sym__upper_identifier] = sym__upper_identifier,
  [sym_string_literal] = sym_string_literal,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_let_assignment] = sym_let_assignment,
  [sym_const_declaration] = sym_const_declaration,
  [sym_type_definition] = sym_type_definition,
  [sym__type_expression] = sym__type_expression,
  [sym_primitive_type] = sym_primitive_type,
  [sym_type_identifier] = sym_type_identifier,
  [sym__expression] = sym__expression,
  [sym__primary_expression] = sym__primary_expression,
  [sym_function_expression] = sym_function_expression,
  [sym_parameter_list] = sym_parameter_list,
  [sym_binary_expression] = sym_binary_expression,
  [sym_identifier] = sym_identifier,
  [sym_tuple_type] = sym_tuple_type,
  [sym_record_type] = sym_record_type,
  [sym_record_field] = sym_record_field,
  [sym_adt_type] = sym_adt_type,
  [sym_adt_option] = sym_adt_option,
  [sym_adt_fields] = sym_adt_fields,
  [sym_adt_field] = sym_adt_field,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_tuple_type_repeat1] = aux_sym_tuple_type_repeat1,
  [aux_sym_record_type_repeat1] = aux_sym_record_type_repeat1,
  [aux_sym_adt_type_repeat1] = aux_sym_adt_type_repeat1,
  [aux_sym_adt_fields_repeat1] = aux_sym_adt_fields_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_number] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_boolean] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym__lower_identifier] = {
    .visible = false,
    .named = true,
  },
  [sym__upper_identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_const_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__type_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__primary_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_function_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_type] = {
    .visible = true,
    .named = true,
  },
  [sym_record_type] = {
    .visible = true,
    .named = true,
  },
  [sym_record_field] = {
    .visible = true,
    .named = true,
  },
  [sym_adt_type] = {
    .visible = true,
    .named = true,
  },
  [sym_adt_option] = {
    .visible = true,
    .named = true,
  },
  [sym_adt_fields] = {
    .visible = true,
    .named = true,
  },
  [sym_adt_field] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tuple_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_adt_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_adt_fields_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_body = 1,
  field_fields = 2,
  field_left = 3,
  field_name = 4,
  field_options = 5,
  field_parameters = 6,
  field_right = 7,
  field_type = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_fields] = "fields",
  [field_left] = "left",
  [field_name] = "name",
  [field_options] = "options",
  [field_parameters] = "parameters",
  [field_right] = "right",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 1},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 2},
  [10] = {.index = 14, .length = 2},
  [11] = {.index = 16, .length = 1},
  [12] = {.index = 17, .length = 1},
  [13] = {.index = 18, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
    {field_value, 3},
  [2] =
    {field_options, 0},
  [3] =
    {field_options, 1},
  [4] =
    {field_options, 0},
    {field_options, 1},
  [6] =
    {field_left, 0},
    {field_right, 2},
  [8] =
    {field_fields, 1},
  [9] =
    {field_options, 1},
    {field_options, 2},
  [11] =
    {field_body, 3},
  [12] =
    {field_fields, 1},
    {field_fields, 2},
  [14] =
    {field_name, 0},
    {field_type, 2},
  [16] =
    {field_type, 2},
  [17] =
    {field_fields, 2},
  [18] =
    {field_body, 4},
    {field_parameters, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(33);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(42);
      if (lookahead == ')') ADVANCE(43);
      if (lookahead == '+') ADVANCE(46);
      if (lookahead == ',') ADVANCE(45);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ':') ADVANCE(57);
      if (lookahead == '=') ADVANCE(36);
      if (lookahead == '[') ADVANCE(53);
      if (lookahead == ']') ADVANCE(54);
      if (lookahead == 'b') ADVANCE(22);
      if (lookahead == 'c') ADVANCE(20);
      if (lookahead == 'l') ADVANCE(11);
      if (lookahead == 'n') ADVANCE(30);
      if (lookahead == 's') ADVANCE(27);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '{') ADVANCE(55);
      if (lookahead == '|') ADVANCE(58);
      if (lookahead == '}') ADVANCE(56);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(48);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(42);
      if (lookahead == ')') ADVANCE(43);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '}') ADVANCE(56);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(48);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(49);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(52);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(51);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(44);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'b') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 13:
      if (lookahead == 'g') ADVANCE(40);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 16:
      if (lookahead == 'm') ADVANCE(8);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 23:
      if (lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 30:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 31:
      if (lookahead == 'y') ADVANCE(23);
      END_STATE();
    case 32:
      if (eof) ADVANCE(33);
      if (lookahead == '(') ADVANCE(42);
      if (lookahead == ')') ADVANCE(43);
      if (lookahead == '+') ADVANCE(46);
      if (lookahead == ',') ADVANCE(45);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ':') ADVANCE(57);
      if (lookahead == '=') ADVANCE(35);
      if (lookahead == ']') ADVANCE(54);
      if (lookahead == 'c') ADVANCE(20);
      if (lookahead == 'l') ADVANCE(11);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '|') ADVANCE(58);
      if (lookahead == '}') ADVANCE(56);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(32)
      END_STATE();
    case 33:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(44);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_number);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_boolean);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym__lower_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__upper_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 32},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 32},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 32},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 32},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 32},
  [91] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_number] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_boolean] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [sym__upper_identifier] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(79),
    [sym__statement] = STATE(14),
    [sym_let_assignment] = STATE(14),
    [sym_const_declaration] = STATE(14),
    [sym_type_definition] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_let] = ACTIONS(7),
    [anon_sym_const] = ACTIONS(9),
    [anon_sym_type] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_RBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    STATE(17), 1,
      sym_adt_option,
    STATE(18), 1,
      sym_type_identifier,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
    STATE(70), 5,
      sym__type_expression,
      sym_primitive_type,
      sym_tuple_type,
      sym_record_type,
      sym_adt_type,
  [37] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(25), 1,
      anon_sym_RBRACK,
    STATE(17), 1,
      sym_adt_option,
    STATE(18), 1,
      sym_type_identifier,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
    STATE(70), 5,
      sym__type_expression,
      sym_primitive_type,
      sym_tuple_type,
      sym_record_type,
      sym_adt_type,
  [74] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    STATE(17), 1,
      sym_adt_option,
    STATE(18), 1,
      sym_type_identifier,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
    STATE(69), 5,
      sym__type_expression,
      sym_primitive_type,
      sym_tuple_type,
      sym_record_type,
      sym_adt_type,
  [108] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    STATE(17), 1,
      sym_adt_option,
    STATE(18), 1,
      sym_type_identifier,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
    STATE(51), 5,
      sym__type_expression,
      sym_primitive_type,
      sym_tuple_type,
      sym_record_type,
      sym_adt_type,
  [142] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    STATE(17), 1,
      sym_adt_option,
    STATE(18), 1,
      sym_type_identifier,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
    STATE(72), 5,
      sym__type_expression,
      sym_primitive_type,
      sym_tuple_type,
      sym_record_type,
      sym_adt_type,
  [176] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    STATE(17), 1,
      sym_adt_option,
    STATE(18), 1,
      sym_type_identifier,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
    STATE(70), 5,
      sym__type_expression,
      sym_primitive_type,
      sym_tuple_type,
      sym_record_type,
      sym_adt_type,
  [210] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 2,
      sym__lower_identifier,
      sym__upper_identifier,
    ACTIONS(31), 2,
      sym_string_literal,
      sym_number,
    STATE(41), 5,
      sym__expression,
      sym__primary_expression,
      sym_function_expression,
      sym_binary_expression,
      sym_identifier,
  [232] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 10,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_EQ,
      anon_sym_const,
      anon_sym_type,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [248] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 2,
      sym__lower_identifier,
      sym__upper_identifier,
    ACTIONS(35), 2,
      sym_string_literal,
      sym_number,
    STATE(42), 5,
      sym__expression,
      sym__primary_expression,
      sym_function_expression,
      sym_binary_expression,
      sym_identifier,
  [270] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 2,
      sym__lower_identifier,
      sym__upper_identifier,
    ACTIONS(37), 2,
      sym_string_literal,
      sym_number,
    STATE(40), 5,
      sym__expression,
      sym__primary_expression,
      sym_function_expression,
      sym_binary_expression,
      sym_identifier,
  [292] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 2,
      sym__lower_identifier,
      sym__upper_identifier,
    ACTIONS(39), 2,
      sym_string_literal,
      sym_number,
    STATE(43), 5,
      sym__expression,
      sym__primary_expression,
      sym_function_expression,
      sym_binary_expression,
      sym_identifier,
  [314] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 2,
      sym__lower_identifier,
      sym__upper_identifier,
    ACTIONS(41), 2,
      sym_string_literal,
      sym_number,
    STATE(45), 5,
      sym__expression,
      sym__primary_expression,
      sym_function_expression,
      sym_binary_expression,
      sym_identifier,
  [336] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_const,
    ACTIONS(11), 1,
      anon_sym_type,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    STATE(15), 5,
      sym__statement,
      sym_let_assignment,
      sym_const_declaration,
      sym_type_definition,
      aux_sym_source_file_repeat1,
  [359] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 1,
      anon_sym_let,
    ACTIONS(50), 1,
      anon_sym_const,
    ACTIONS(53), 1,
      anon_sym_type,
    STATE(15), 5,
      sym__statement,
      sym_let_assignment,
      sym_const_declaration,
      sym_type_definition,
      aux_sym_source_file_repeat1,
  [382] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 9,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_EQ,
      anon_sym_const,
      anon_sym_type,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_COLON,
  [397] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_PIPE,
    STATE(23), 1,
      aux_sym_adt_type_repeat1,
    ACTIONS(58), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [416] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_PIPE,
    ACTIONS(62), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [435] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [452] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_PIPE,
    STATE(22), 1,
      aux_sym_adt_type_repeat1,
    ACTIONS(69), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [471] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_PIPE,
    STATE(20), 1,
      aux_sym_adt_type_repeat1,
    ACTIONS(71), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [490] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_PIPE,
    STATE(22), 1,
      aux_sym_adt_type_repeat1,
    ACTIONS(73), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [509] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_PIPE,
    STATE(22), 1,
      aux_sym_adt_type_repeat1,
    ACTIONS(78), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [528] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [542] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [556] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [570] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [584] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [597] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [610] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [623] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [636] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [649] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [662] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [675] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [688] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_LBRACE,
    STATE(85), 1,
      sym_primitive_type,
    STATE(88), 1,
      sym_adt_fields,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
  [706] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    STATE(73), 2,
      sym_primitive_type,
      sym_type_identifier,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
  [722] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_RPAREN,
    STATE(63), 1,
      sym_identifier,
    STATE(82), 1,
      sym_parameter_list,
    ACTIONS(29), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [739] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      sym_record_field,
    STATE(80), 1,
      sym_identifier,
    ACTIONS(29), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [756] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 5,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_PLUS,
  [767] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_PLUS,
    ACTIONS(110), 4,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
  [780] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_PLUS,
    ACTIONS(114), 4,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
  [793] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_PLUS,
    ACTIONS(116), 4,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
  [806] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      sym_record_field,
    STATE(80), 1,
      sym_identifier,
    ACTIONS(29), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [823] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_PLUS,
    ACTIONS(120), 4,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
  [836] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_RBRACE,
    STATE(74), 1,
      sym_adt_field,
    STATE(81), 1,
      sym_identifier,
    ACTIONS(29), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [853] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_RBRACE,
    STATE(74), 1,
      sym_adt_field,
    STATE(81), 1,
      sym_identifier,
    ACTIONS(29), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [870] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(74), 1,
      sym_adt_field,
    STATE(81), 1,
      sym_identifier,
    ACTIONS(29), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [884] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(62), 1,
      sym_record_field,
    STATE(80), 1,
      sym_identifier,
    ACTIONS(29), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [898] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(60), 1,
      sym_adt_field,
    STATE(81), 1,
      sym_identifier,
    ACTIONS(29), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [912] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 4,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
  [922] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(75), 1,
      sym_record_field,
    STATE(80), 1,
      sym_identifier,
    ACTIONS(29), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [936] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(78), 1,
      sym_identifier,
    ACTIONS(29), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [947] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(71), 1,
      sym_identifier,
    ACTIONS(29), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [958] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      anon_sym_RPAREN,
    ACTIONS(130), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_parameter_list_repeat1,
  [971] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      anon_sym_RPAREN,
    ACTIONS(134), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_parameter_list_repeat1,
  [984] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      anon_sym_COMMA,
    ACTIONS(140), 1,
      anon_sym_RBRACK,
    STATE(57), 1,
      aux_sym_tuple_type_repeat1,
  [997] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_COMMA,
    ACTIONS(144), 1,
      anon_sym_RBRACK,
    STATE(57), 1,
      aux_sym_tuple_type_repeat1,
  [1010] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    ACTIONS(149), 1,
      anon_sym_RBRACE,
    STATE(59), 1,
      aux_sym_record_type_repeat1,
  [1023] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_COMMA,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym_adt_fields_repeat1,
  [1036] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    STATE(19), 1,
      sym_type_identifier,
    STATE(25), 1,
      sym_adt_option,
  [1049] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_COMMA,
    ACTIONS(157), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      aux_sym_record_type_repeat1,
  [1062] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_COMMA,
    ACTIONS(159), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      aux_sym_parameter_list_repeat1,
  [1075] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_COMMA,
    ACTIONS(163), 1,
      anon_sym_RBRACE,
    STATE(59), 1,
      aux_sym_record_type_repeat1,
  [1088] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(83), 1,
      sym_identifier,
    ACTIONS(29), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [1099] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(167), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_adt_fields_repeat1,
  [1112] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_COMMA,
    ACTIONS(172), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_adt_fields_repeat1,
  [1125] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    STATE(19), 1,
      sym_type_identifier,
    STATE(21), 1,
      sym_adt_option,
  [1138] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_COMMA,
    ACTIONS(176), 1,
      anon_sym_RBRACK,
    STATE(58), 1,
      aux_sym_tuple_type_repeat1,
  [1151] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1159] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1167] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1175] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1183] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1191] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1199] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    STATE(90), 1,
      sym_type_identifier,
  [1209] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_EQ_GT,
  [1216] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_EQ,
  [1223] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
  [1230] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_COLON,
  [1237] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_COLON,
  [1244] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_RPAREN,
  [1251] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_EQ,
  [1258] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      anon_sym_EQ_GT,
  [1265] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_RPAREN,
  [1272] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
  [1279] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_RPAREN,
  [1286] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
  [1293] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
  [1300] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_EQ,
  [1307] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 74,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 142,
  [SMALL_STATE(7)] = 176,
  [SMALL_STATE(8)] = 210,
  [SMALL_STATE(9)] = 232,
  [SMALL_STATE(10)] = 248,
  [SMALL_STATE(11)] = 270,
  [SMALL_STATE(12)] = 292,
  [SMALL_STATE(13)] = 314,
  [SMALL_STATE(14)] = 336,
  [SMALL_STATE(15)] = 359,
  [SMALL_STATE(16)] = 382,
  [SMALL_STATE(17)] = 397,
  [SMALL_STATE(18)] = 416,
  [SMALL_STATE(19)] = 435,
  [SMALL_STATE(20)] = 452,
  [SMALL_STATE(21)] = 471,
  [SMALL_STATE(22)] = 490,
  [SMALL_STATE(23)] = 509,
  [SMALL_STATE(24)] = 528,
  [SMALL_STATE(25)] = 542,
  [SMALL_STATE(26)] = 556,
  [SMALL_STATE(27)] = 570,
  [SMALL_STATE(28)] = 584,
  [SMALL_STATE(29)] = 597,
  [SMALL_STATE(30)] = 610,
  [SMALL_STATE(31)] = 623,
  [SMALL_STATE(32)] = 636,
  [SMALL_STATE(33)] = 649,
  [SMALL_STATE(34)] = 662,
  [SMALL_STATE(35)] = 675,
  [SMALL_STATE(36)] = 688,
  [SMALL_STATE(37)] = 706,
  [SMALL_STATE(38)] = 722,
  [SMALL_STATE(39)] = 739,
  [SMALL_STATE(40)] = 756,
  [SMALL_STATE(41)] = 767,
  [SMALL_STATE(42)] = 780,
  [SMALL_STATE(43)] = 793,
  [SMALL_STATE(44)] = 806,
  [SMALL_STATE(45)] = 823,
  [SMALL_STATE(46)] = 836,
  [SMALL_STATE(47)] = 853,
  [SMALL_STATE(48)] = 870,
  [SMALL_STATE(49)] = 884,
  [SMALL_STATE(50)] = 898,
  [SMALL_STATE(51)] = 912,
  [SMALL_STATE(52)] = 922,
  [SMALL_STATE(53)] = 936,
  [SMALL_STATE(54)] = 947,
  [SMALL_STATE(55)] = 958,
  [SMALL_STATE(56)] = 971,
  [SMALL_STATE(57)] = 984,
  [SMALL_STATE(58)] = 997,
  [SMALL_STATE(59)] = 1010,
  [SMALL_STATE(60)] = 1023,
  [SMALL_STATE(61)] = 1036,
  [SMALL_STATE(62)] = 1049,
  [SMALL_STATE(63)] = 1062,
  [SMALL_STATE(64)] = 1075,
  [SMALL_STATE(65)] = 1088,
  [SMALL_STATE(66)] = 1099,
  [SMALL_STATE(67)] = 1112,
  [SMALL_STATE(68)] = 1125,
  [SMALL_STATE(69)] = 1138,
  [SMALL_STATE(70)] = 1151,
  [SMALL_STATE(71)] = 1159,
  [SMALL_STATE(72)] = 1167,
  [SMALL_STATE(73)] = 1175,
  [SMALL_STATE(74)] = 1183,
  [SMALL_STATE(75)] = 1191,
  [SMALL_STATE(76)] = 1199,
  [SMALL_STATE(77)] = 1209,
  [SMALL_STATE(78)] = 1216,
  [SMALL_STATE(79)] = 1223,
  [SMALL_STATE(80)] = 1230,
  [SMALL_STATE(81)] = 1237,
  [SMALL_STATE(82)] = 1244,
  [SMALL_STATE(83)] = 1251,
  [SMALL_STATE(84)] = 1258,
  [SMALL_STATE(85)] = 1265,
  [SMALL_STATE(86)] = 1272,
  [SMALL_STATE(87)] = 1279,
  [SMALL_STATE(88)] = 1286,
  [SMALL_STATE(89)] = 1293,
  [SMALL_STATE(90)] = 1300,
  [SMALL_STATE(91)] = 1307,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_identifier, 1),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(53),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(65),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(76),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_type, 1, .production_id = 2),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__type_expression, 1), REDUCE(sym_adt_option, 1),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_option, 1),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_type, 3, .production_id = 7),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_type, 2, .production_id = 3),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_adt_type_repeat1, 2),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_adt_type_repeat1, 2), SHIFT_REPEAT(61),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_type, 2, .production_id = 4),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_option, 4, .production_id = 11),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_option, 4, .production_id = 12),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 3, .production_id = 6),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 3, .production_id = 6),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 4, .production_id = 6),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 4, .production_id = 9),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 4, .production_id = 6),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 5, .production_id = 9),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 4, .production_id = 9),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 5, .production_id = 9),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 5),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_declaration, 4, .production_id = 1),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_assignment, 4, .production_id = 1),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_expression, 4, .production_id = 8),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_expression, 5, .production_id = 13),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 4, .production_id = 1),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(54),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2), SHIFT_REPEAT(7),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_type_repeat1, 2), SHIFT_REPEAT(52),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_type_repeat1, 2),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_adt_fields_repeat1, 2), SHIFT_REPEAT(48),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_adt_fields_repeat1, 2),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_field, 3, .production_id = 10),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_field, 3, .production_id = 10),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [186] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_fields, 3, .production_id = 6),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_fields, 4, .production_id = 6),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_fields, 4, .production_id = 9),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_fields, 5, .production_id = 9),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_chicory(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
