#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 77
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 11

enum {
  anon_sym_let = 1,
  anon_sym_EQ = 2,
  anon_sym_const = 3,
  anon_sym_type = 4,
  anon_sym_number = 5,
  anon_sym_string = 6,
  anon_sym_boolean = 7,
  sym__lower_identifier = 8,
  sym__upper_identifier = 9,
  sym_string_literal = 10,
  sym_number = 11,
  sym_comment = 12,
  anon_sym_LBRACK = 13,
  anon_sym_COMMA = 14,
  anon_sym_RBRACK = 15,
  anon_sym_LBRACE = 16,
  anon_sym_RBRACE = 17,
  anon_sym_COLON = 18,
  anon_sym_PIPE = 19,
  anon_sym_LPAREN = 20,
  anon_sym_RPAREN = 21,
  sym_source_file = 22,
  sym__statement = 23,
  sym_let_assignment = 24,
  sym_const_declaration = 25,
  sym_type_definition = 26,
  sym__type_expression = 27,
  sym_primitive_type = 28,
  sym_type_identifier = 29,
  sym__expression = 30,
  sym__primary_expression = 31,
  sym_identifier = 32,
  sym_tuple_type = 33,
  sym_record_type = 34,
  sym_record_field = 35,
  sym_adt_type = 36,
  sym_adt_option = 37,
  sym_adt_fields = 38,
  sym_adt_field = 39,
  aux_sym_source_file_repeat1 = 40,
  aux_sym_tuple_type_repeat1 = 41,
  aux_sym_record_type_repeat1 = 42,
  aux_sym_adt_type_repeat1 = 43,
  aux_sym_adt_fields_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_const] = "const",
  [anon_sym_type] = "type",
  [anon_sym_number] = "number",
  [anon_sym_string] = "string",
  [anon_sym_boolean] = "boolean",
  [sym__lower_identifier] = "_lower_identifier",
  [sym__upper_identifier] = "_upper_identifier",
  [sym_string_literal] = "string_literal",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_PIPE] = "|",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_let_assignment] = "let_assignment",
  [sym_const_declaration] = "const_declaration",
  [sym_type_definition] = "type_definition",
  [sym__type_expression] = "_type_expression",
  [sym_primitive_type] = "primitive_type",
  [sym_type_identifier] = "type_identifier",
  [sym__expression] = "_expression",
  [sym__primary_expression] = "_primary_expression",
  [sym_identifier] = "identifier",
  [sym_tuple_type] = "tuple_type",
  [sym_record_type] = "record_type",
  [sym_record_field] = "record_field",
  [sym_adt_type] = "adt_type",
  [sym_adt_option] = "adt_option",
  [sym_adt_fields] = "adt_fields",
  [sym_adt_field] = "adt_field",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_tuple_type_repeat1] = "tuple_type_repeat1",
  [aux_sym_record_type_repeat1] = "record_type_repeat1",
  [aux_sym_adt_type_repeat1] = "adt_type_repeat1",
  [aux_sym_adt_fields_repeat1] = "adt_fields_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_number] = anon_sym_number,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_boolean] = anon_sym_boolean,
  [sym__lower_identifier] = sym__lower_identifier,
  [sym__upper_identifier] = sym__upper_identifier,
  [sym_string_literal] = sym_string_literal,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_let_assignment] = sym_let_assignment,
  [sym_const_declaration] = sym_const_declaration,
  [sym_type_definition] = sym_type_definition,
  [sym__type_expression] = sym__type_expression,
  [sym_primitive_type] = sym_primitive_type,
  [sym_type_identifier] = sym_type_identifier,
  [sym__expression] = sym__expression,
  [sym__primary_expression] = sym__primary_expression,
  [sym_identifier] = sym_identifier,
  [sym_tuple_type] = sym_tuple_type,
  [sym_record_type] = sym_record_type,
  [sym_record_field] = sym_record_field,
  [sym_adt_type] = sym_adt_type,
  [sym_adt_option] = sym_adt_option,
  [sym_adt_fields] = sym_adt_fields,
  [sym_adt_field] = sym_adt_field,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_tuple_type_repeat1] = aux_sym_tuple_type_repeat1,
  [aux_sym_record_type_repeat1] = aux_sym_record_type_repeat1,
  [aux_sym_adt_type_repeat1] = aux_sym_adt_type_repeat1,
  [aux_sym_adt_fields_repeat1] = aux_sym_adt_fields_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_number] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_boolean] = {
    .visible = true,
    .named = false,
  },
  [sym__lower_identifier] = {
    .visible = false,
    .named = true,
  },
  [sym__upper_identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_const_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__type_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__primary_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_type] = {
    .visible = true,
    .named = true,
  },
  [sym_record_type] = {
    .visible = true,
    .named = true,
  },
  [sym_record_field] = {
    .visible = true,
    .named = true,
  },
  [sym_adt_type] = {
    .visible = true,
    .named = true,
  },
  [sym_adt_option] = {
    .visible = true,
    .named = true,
  },
  [sym_adt_fields] = {
    .visible = true,
    .named = true,
  },
  [sym_adt_field] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tuple_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_adt_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_adt_fields_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_fields = 1,
  field_name = 2,
  field_options = 3,
  field_type = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_fields] = "fields",
  [field_name] = "name",
  [field_options] = "options",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 1},
  [10] = {.index = 14, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
    {field_value, 3},
  [2] =
    {field_options, 0},
  [3] =
    {field_options, 1},
  [4] =
    {field_options, 0},
    {field_options, 1},
  [6] =
    {field_fields, 1},
  [7] =
    {field_options, 1},
    {field_options, 2},
  [9] =
    {field_fields, 1},
    {field_fields, 2},
  [11] =
    {field_name, 0},
    {field_type, 2},
  [13] =
    {field_type, 2},
  [14] =
    {field_fields, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(52);
      if (lookahead == ')') ADVANCE(53);
      if (lookahead == ',') ADVANCE(46);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ':') ADVANCE(50);
      if (lookahead == '=') ADVANCE(33);
      if (lookahead == '[') ADVANCE(45);
      if (lookahead == ']') ADVANCE(47);
      if (lookahead == 'b') ADVANCE(21);
      if (lookahead == 'c') ADVANCE(19);
      if (lookahead == 'l') ADVANCE(10);
      if (lookahead == 'n') ADVANCE(29);
      if (lookahead == 's') ADVANCE(26);
      if (lookahead == 't') ADVANCE(30);
      if (lookahead == '{') ADVANCE(48);
      if (lookahead == '|') ADVANCE(51);
      if (lookahead == '}') ADVANCE(49);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(40);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '}') ADVANCE(49);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(40);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(44);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'b') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 12:
      if (lookahead == 'g') ADVANCE(37);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 15:
      if (lookahead == 'm') ADVANCE(7);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(25);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(8);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 25:
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 30:
      if (lookahead == 'y') ADVANCE(22);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_number);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_boolean);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__lower_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__upper_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_number] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_boolean] = ACTIONS(1),
    [sym__upper_identifier] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(66),
    [sym__statement] = STATE(9),
    [sym_let_assignment] = STATE(9),
    [sym_const_declaration] = STATE(9),
    [sym_type_definition] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_let] = ACTIONS(7),
    [anon_sym_const] = ACTIONS(9),
    [anon_sym_type] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_RBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    STATE(12), 1,
      sym_type_identifier,
    STATE(13), 1,
      sym_adt_option,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
    STATE(61), 5,
      sym__type_expression,
      sym_primitive_type,
      sym_tuple_type,
      sym_record_type,
      sym_adt_type,
  [37] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(25), 1,
      anon_sym_RBRACK,
    STATE(12), 1,
      sym_type_identifier,
    STATE(13), 1,
      sym_adt_option,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
    STATE(61), 5,
      sym__type_expression,
      sym_primitive_type,
      sym_tuple_type,
      sym_record_type,
      sym_adt_type,
  [74] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    STATE(12), 1,
      sym_type_identifier,
    STATE(13), 1,
      sym_adt_option,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
    STATE(49), 5,
      sym__type_expression,
      sym_primitive_type,
      sym_tuple_type,
      sym_record_type,
      sym_adt_type,
  [108] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    STATE(12), 1,
      sym_type_identifier,
    STATE(13), 1,
      sym_adt_option,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
    STATE(44), 5,
      sym__type_expression,
      sym_primitive_type,
      sym_tuple_type,
      sym_record_type,
      sym_adt_type,
  [142] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    STATE(12), 1,
      sym_type_identifier,
    STATE(13), 1,
      sym_adt_option,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
    STATE(59), 5,
      sym__type_expression,
      sym_primitive_type,
      sym_tuple_type,
      sym_record_type,
      sym_adt_type,
  [176] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    STATE(12), 1,
      sym_type_identifier,
    STATE(13), 1,
      sym_adt_option,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
    STATE(61), 5,
      sym__type_expression,
      sym_primitive_type,
      sym_tuple_type,
      sym_record_type,
      sym_adt_type,
  [210] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 10,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_EQ,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_LPAREN,
  [226] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_const,
    ACTIONS(11), 1,
      anon_sym_type,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    STATE(11), 5,
      sym__statement,
      sym_let_assignment,
      sym_const_declaration,
      sym_type_definition,
      aux_sym_source_file_repeat1,
  [249] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [266] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      anon_sym_let,
    ACTIONS(40), 1,
      anon_sym_const,
    ACTIONS(43), 1,
      anon_sym_type,
    STATE(11), 5,
      sym__statement,
      sym_let_assignment,
      sym_const_declaration,
      sym_type_definition,
      aux_sym_source_file_repeat1,
  [289] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_PIPE,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [308] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_PIPE,
    STATE(15), 1,
      aux_sym_adt_type_repeat1,
    ACTIONS(49), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [327] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_PIPE,
    STATE(17), 1,
      aux_sym_adt_type_repeat1,
    ACTIONS(53), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [346] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_PIPE,
    STATE(16), 1,
      aux_sym_adt_type_repeat1,
    ACTIONS(55), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [365] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_PIPE,
    STATE(16), 1,
      aux_sym_adt_type_repeat1,
    ACTIONS(57), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [384] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_PIPE,
    STATE(16), 1,
      aux_sym_adt_type_repeat1,
    ACTIONS(62), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [403] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
  [417] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [431] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [445] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PIPE,
  [459] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 2,
      sym__lower_identifier,
      sym__upper_identifier,
    ACTIONS(72), 2,
      sym_string_literal,
      sym_number,
    STATE(40), 3,
      sym__expression,
      sym__primary_expression,
      sym_identifier,
  [476] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 2,
      sym__lower_identifier,
      sym__upper_identifier,
    ACTIONS(74), 2,
      sym_string_literal,
      sym_number,
    STATE(43), 3,
      sym__expression,
      sym__primary_expression,
      sym_identifier,
  [493] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [506] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [519] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [532] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [545] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [558] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [571] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [584] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [597] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 6,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_EQ,
      anon_sym_const,
      anon_sym_type,
      anon_sym_COLON,
  [609] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_LBRACE,
    STATE(70), 1,
      sym_adt_fields,
    STATE(71), 1,
      sym_primitive_type,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
  [627] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    STATE(64), 2,
      sym_primitive_type,
      sym_type_identifier,
    ACTIONS(13), 3,
      anon_sym_number,
      anon_sym_string,
      anon_sym_boolean,
  [643] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_RBRACE,
    STATE(63), 1,
      sym_adt_field,
    STATE(65), 1,
      sym_identifier,
    ACTIONS(70), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [660] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    STATE(60), 1,
      sym_record_field,
    STATE(67), 1,
      sym_identifier,
    ACTIONS(70), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [677] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    STATE(63), 1,
      sym_adt_field,
    STATE(65), 1,
      sym_identifier,
    ACTIONS(70), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [694] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    STATE(60), 1,
      sym_record_field,
    STATE(67), 1,
      sym_identifier,
    ACTIONS(70), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [711] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(52), 1,
      sym_adt_field,
    STATE(65), 1,
      sym_identifier,
    ACTIONS(70), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [725] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 4,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
  [735] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(60), 1,
      sym_record_field,
    STATE(67), 1,
      sym_identifier,
    ACTIONS(70), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [749] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(48), 1,
      sym_record_field,
    STATE(67), 1,
      sym_identifier,
    ACTIONS(70), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [763] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 4,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
  [773] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 4,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_const,
      anon_sym_type,
  [783] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(63), 1,
      sym_adt_field,
    STATE(65), 1,
      sym_identifier,
    ACTIONS(70), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [797] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(112), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      aux_sym_adt_fields_repeat1,
  [810] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(72), 1,
      sym_identifier,
    ACTIONS(70), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [821] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      aux_sym_record_type_repeat1,
  [834] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_COMMA,
    ACTIONS(120), 1,
      anon_sym_RBRACK,
    STATE(57), 1,
      aux_sym_tuple_type_repeat1,
  [847] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_COMMA,
    ACTIONS(125), 1,
      anon_sym_RBRACK,
    STATE(50), 1,
      aux_sym_tuple_type_repeat1,
  [860] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_COMMA,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    STATE(53), 1,
      aux_sym_record_type_repeat1,
  [873] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(133), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      aux_sym_adt_fields_repeat1,
  [886] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
    STATE(53), 1,
      aux_sym_record_type_repeat1,
  [899] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(68), 1,
      sym_identifier,
    ACTIONS(70), 2,
      sym__lower_identifier,
      sym__upper_identifier,
  [910] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    STATE(10), 1,
      sym_type_identifier,
    STATE(21), 1,
      sym_adt_option,
  [923] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    STATE(10), 1,
      sym_type_identifier,
    STATE(14), 1,
      sym_adt_option,
  [936] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_COMMA,
    ACTIONS(142), 1,
      anon_sym_RBRACK,
    STATE(50), 1,
      aux_sym_tuple_type_repeat1,
  [949] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_COMMA,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      aux_sym_adt_fields_repeat1,
  [962] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [970] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [978] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [986] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__upper_identifier,
    STATE(76), 1,
      sym_type_identifier,
  [996] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1004] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1012] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_COLON,
  [1019] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      ts_builtin_sym_end,
  [1026] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_COLON,
  [1033] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_EQ,
  [1040] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
  [1047] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_RPAREN,
  [1054] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
  [1061] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_EQ,
  [1068] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
  [1075] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_RPAREN,
  [1082] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_RPAREN,
  [1089] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 74,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 142,
  [SMALL_STATE(7)] = 176,
  [SMALL_STATE(8)] = 210,
  [SMALL_STATE(9)] = 226,
  [SMALL_STATE(10)] = 249,
  [SMALL_STATE(11)] = 266,
  [SMALL_STATE(12)] = 289,
  [SMALL_STATE(13)] = 308,
  [SMALL_STATE(14)] = 327,
  [SMALL_STATE(15)] = 346,
  [SMALL_STATE(16)] = 365,
  [SMALL_STATE(17)] = 384,
  [SMALL_STATE(18)] = 403,
  [SMALL_STATE(19)] = 417,
  [SMALL_STATE(20)] = 431,
  [SMALL_STATE(21)] = 445,
  [SMALL_STATE(22)] = 459,
  [SMALL_STATE(23)] = 476,
  [SMALL_STATE(24)] = 493,
  [SMALL_STATE(25)] = 506,
  [SMALL_STATE(26)] = 519,
  [SMALL_STATE(27)] = 532,
  [SMALL_STATE(28)] = 545,
  [SMALL_STATE(29)] = 558,
  [SMALL_STATE(30)] = 571,
  [SMALL_STATE(31)] = 584,
  [SMALL_STATE(32)] = 597,
  [SMALL_STATE(33)] = 609,
  [SMALL_STATE(34)] = 627,
  [SMALL_STATE(35)] = 643,
  [SMALL_STATE(36)] = 660,
  [SMALL_STATE(37)] = 677,
  [SMALL_STATE(38)] = 694,
  [SMALL_STATE(39)] = 711,
  [SMALL_STATE(40)] = 725,
  [SMALL_STATE(41)] = 735,
  [SMALL_STATE(42)] = 749,
  [SMALL_STATE(43)] = 763,
  [SMALL_STATE(44)] = 773,
  [SMALL_STATE(45)] = 783,
  [SMALL_STATE(46)] = 797,
  [SMALL_STATE(47)] = 810,
  [SMALL_STATE(48)] = 821,
  [SMALL_STATE(49)] = 834,
  [SMALL_STATE(50)] = 847,
  [SMALL_STATE(51)] = 860,
  [SMALL_STATE(52)] = 873,
  [SMALL_STATE(53)] = 886,
  [SMALL_STATE(54)] = 899,
  [SMALL_STATE(55)] = 910,
  [SMALL_STATE(56)] = 923,
  [SMALL_STATE(57)] = 936,
  [SMALL_STATE(58)] = 949,
  [SMALL_STATE(59)] = 962,
  [SMALL_STATE(60)] = 970,
  [SMALL_STATE(61)] = 978,
  [SMALL_STATE(62)] = 986,
  [SMALL_STATE(63)] = 996,
  [SMALL_STATE(64)] = 1004,
  [SMALL_STATE(65)] = 1012,
  [SMALL_STATE(66)] = 1019,
  [SMALL_STATE(67)] = 1026,
  [SMALL_STATE(68)] = 1033,
  [SMALL_STATE(69)] = 1040,
  [SMALL_STATE(70)] = 1047,
  [SMALL_STATE(71)] = 1054,
  [SMALL_STATE(72)] = 1061,
  [SMALL_STATE(73)] = 1068,
  [SMALL_STATE(74)] = 1075,
  [SMALL_STATE(75)] = 1082,
  [SMALL_STATE(76)] = 1089,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_identifier, 1),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_option, 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(47),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(54),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(62),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__type_expression, 1), REDUCE(sym_adt_option, 1),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_type, 1, .production_id = 2),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_type, 2, .production_id = 3),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_type, 2, .production_id = 4),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_adt_type_repeat1, 2),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_adt_type_repeat1, 2), SHIFT_REPEAT(55),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_type, 3, .production_id = 6),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_option, 4, .production_id = 9),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_option, 4, .production_id = 10),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 4, .production_id = 5),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 3, .production_id = 5),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 4, .production_id = 5),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 4, .production_id = 7),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 4, .production_id = 7),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 3, .production_id = 5),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 5, .production_id = 7),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 5, .production_id = 7),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_declaration, 4, .production_id = 1),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_assignment, 4, .production_id = 1),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 4, .production_id = 1),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2), SHIFT_REPEAT(7),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_type_repeat1, 2), SHIFT_REPEAT(41),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_type_repeat1, 2),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_adt_fields_repeat1, 2), SHIFT_REPEAT(45),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_adt_fields_repeat1, 2),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_field, 3, .production_id = 8),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_field, 3, .production_id = 8),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [155] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_fields, 3, .production_id = 5),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_fields, 4, .production_id = 5),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_fields, 4, .production_id = 7),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adt_fields, 5, .production_id = 7),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_chicory(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
